# -*- coding: utf-8 -*-
"""arabic_poem_emotion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159iufK9wvKQNnbIwGgvKUypRiHv0DzVD

# ***Arabic Poetry Emotion Classification Using NLP and Machine Learning Techniques***

**Abstract**

This project presents a Natural Language Processing (NLP) and Machine Learning approach for classifying emotions in Arabic poetry. The objective is to automatically identify the emotional category expressed in a poem as joy, love, or sadness. A labeled dataset of Arabic poems was collected and preprocessed through text cleaning, normalization of Arabic characters, removal of diacritics, punctuation filtering, and whitespace normalization. To ensure fair class representation, the dataset was balanced across all emotion categories. Text features were extracted using the **TF-IDF** (Term Frequency–Inverse Document Frequency) technique with unigrams, bigrams, and trigrams, allowing the model to capture both individual words and contextual phrases. Multiple machine learning models were evaluated, including **Naive Bayes and Logistic Regression**, with the final optimized Logistic Regression model achieving approximately **60.7%** classification accuracy. The project also includes an interactive prediction function that allows users to input new Arabic poems and receive emotion predictions. The results demonstrate both the potential and challenges of emotion classification in Arabic poetic language due to its rich metaphorical and emotionally blended nature.

**Introduction**

Emotion is one of the strongest elements in poetry, where language is often used to express feelings such as love, sadness, longing, and joy in rich and symbolic forms. Arabic poetry, in particular, is known for its deep emotional expression, complex vocabulary, and stylistic beauty, making it an interesting domain for Natural Language Processing (NLP) applications.

Emotion classification is a text mining task that aims to automatically identify the emotional category of a given text. While emotion detection has been widely studied in areas such as social media analysis, customer reviews, and sentiment analysis, its application to Arabic poetry remains relatively challenging due to figurative language, semantic ambiguity, and the overlap between emotional expressions.

This project focuses on building a machine learning model capable of classifying Arabic poems into three emotional categories: joy, love, and sadness. The study applies a complete NLP pipeline, including text preprocessing, feature extraction using TF-IDF, and supervised machine learning classification. Different models were explored and evaluated to determine the most effective approach for this task.

The goal of this project is not only to classify poetic emotions accurately, but also to explore how machine learning interprets complex emotional language in Arabic literary texts.
"""

# Connecting Google Drive to Colab
from google.colab import drive
drive.mount('/content/drive')

# Basic libraries
import pandas as pd
import numpy as np

# Text processing
import re
import string

# Machine learning
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Models
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import os
os.listdir('/content/drive/MyDrive/Colab Notebooks/data')

file_path = '/content/drive/MyDrive/Colab Notebooks/data/Arabic Poems dataset.csv'

# Read using latin1 first
df = pd.read_csv(file_path, encoding='latin1')

# Fix broken Arabic text
def fix_arabic_text(text):
    try:
        return text.encode('latin1').decode('utf-8', errors='ignore')
    except:
        return text

df['poem'] = df['poem'].apply(fix_arabic_text)

df.head(10)

# Dataset shape (rows, columns)
print("Shape:", df.shape)

print("\n" + "="*50)

# Column names
print("Columns:")
print(df.columns)

print("\n" + "="*50)

# Missing values
print("Missing values:")
print(df.isnull().sum())

print("\n" + "="*50)

# Emotion distribution
print("Emotion counts:")
print(df['emotion'].value_counts())

#cleaning..
# Keep only rows with poem + emotion
df = df.dropna(subset=['poem', 'emotion'])

# Reset index
df = df.reset_index(drop=True)

# Check again
print(df.isnull().sum())
print("\nShape after cleaning:", df.shape)

#Arabic words normalaization

def clean_arabic_text(text):
    # Convert to string
    text = str(text)

    # Remove Arabic diacritics (tashkeel)
    text = re.sub(r'[\u0617-\u061A\u064B-\u0652]', '', text)

    # Normalize Arabic letters
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ؤ', 'و', text)
    text = re.sub(r'ئ', 'ي', text)
    text = re.sub(r'ة', 'ه', text)

    # Remove non-Arabic characters, numbers, punctuation
    text = re.sub(r'[^ء-ي\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Create cleaned version of poems
df['clean_poem'] = df['poem'].apply(clean_arabic_text)

# Show original vs cleaned
df[['poem', 'clean_poem']].head(10)

df[['poem', 'clean_poem', 'emotion']].head()

# Input text (features)
X = df['clean_poem']

# Target label (what we want to predict)
y = df['emotion']

print("First poem:")
print(X.iloc[0])

print("\nEmotion:")
print(y.iloc[0])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

nb_predictions = nb_model.predict(X_test_tfidf)

print("Naive Bayes model trained successfully.")

nb_accuracy = accuracy_score(y_test, nb_predictions)

print("Naive Bayes Accuracy:", nb_accuracy)

print(classification_report(y_test, nb_predictions))

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_tfidf, y_train)

lr_predictions = lr_model.predict(X_test_tfidf)

print("Logistic Regression model trained successfully.")

lr_accuracy = accuracy_score(y_test, lr_predictions)

print("Logistic Regression Accuracy:", lr_accuracy)

print(classification_report(y_test, lr_predictions))

def predict_emotion(poem):
    # Clean poem
    cleaned = clean_arabic_text(poem)

    # Convert to TF-IDF
    poem_vector = tfidf.transform([cleaned])

    # Predict
    prediction = lr_model.predict(poem_vector)[0]

    return prediction

new_poem = "أحببتُكِ حبًّا لو تكلّمَ، لقال للعالم: ما خُلِقَ الوفاءُ إلا لها."
predict_emotion(new_poem)

balanced_lr_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

balanced_lr_model.fit(X_train_tfidf, y_train)

balanced_lr_predictions = balanced_lr_model.predict(X_test_tfidf)

print("Balanced Logistic Regression trained successfully.")

balanced_accuracy = accuracy_score(y_test, balanced_lr_predictions)

print("Balanced Logistic Regression Accuracy:", balanced_accuracy)
print(classification_report(y_test, balanced_lr_predictions))

def predict_emotion_balanced(poem):
    cleaned = clean_arabic_text(poem)
    poem_vector = tfidf.transform([cleaned])
    prediction = balanced_lr_model.predict(poem_vector)[0]
    return prediction

new_poem = "وما كنت ممن يدخل العشق قلبه/ ولكن من يبصر جفونك يعشق"
predict_emotion_balanced(new_poem)

"""----------------- bias towreds sad"""

balanced_df = df.groupby('emotion', group_keys=False).apply(
    lambda x: x.sample(n=1900, random_state=42)
)

balanced_df['emotion'].value_counts()

X = balanced_df['clean_poem']
y = balanced_df['emotion']

print(balanced_df['emotion'].value_counts())
print("Shape:", balanced_df.shape)

X = balanced_df['clean_poem']
y = balanced_df['emotion']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print(y_train.value_counts())

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training shape:", X_train_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)

lr_model_balanced_data = LogisticRegression(max_iter=1000)

lr_model_balanced_data.fit(X_train_tfidf, y_train)

lr_balanced_data_predictions = lr_model_balanced_data.predict(X_test_tfidf)

print("Model trained on balanced data successfully.")

balanced_data_accuracy = accuracy_score(y_test, lr_balanced_data_predictions)

print("Balanced Dataset Logistic Regression Accuracy:", balanced_data_accuracy)
print(classification_report(y_test, lr_balanced_data_predictions))

"""**Results and Evaluation**

The final optimized Logistic Regression model, trained on a balanced dataset and enhanced with TF-IDF feature extraction using unigrams, bigrams, and trigrams, achieved a classification accuracy of 60.7%.

Performance varied across emotion classes:

- Joy achieved the highest recall (71%) and F1-score (0.66), making it the most distinguishable class.
- Love achieved moderate and balanced performance with an F1-score of 0.59.
- Sadness achieved the lowest recall (51%), indicating overlap with other emotional categories.

The confusion matrix further revealed notable class overlap, particularly between love and sadness, reflecting the blended emotional nature of Arabic poetry.
"""

def predict_emotion_final(poem):
    cleaned = clean_arabic_text(poem)
    poem_vector = tfidf.transform([cleaned])
    prediction = lr_model_balanced_data.predict(poem_vector)[0]
    return prediction

new_poem = "أحببتُكِ حبًّا لو تكلّمَ، لقال للعالم: ما خُلِقَ الوفاءُ إلا لها."
predict_emotion_final(new_poem)

"""***here shows the model is still not preforming well ..***


"""

tfidf = TfidfVectorizer(
    max_features=7000,
    ngram_range=(1, 3)
)

tfidf = TfidfVectorizer(
    max_features=7000,
    ngram_range=(1, 3)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

lr_model_balanced_data = LogisticRegression(max_iter=1000)

lr_model_balanced_data.fit(X_train_tfidf, y_train)

lr_balanced_data_predictions = lr_model_balanced_data.predict(X_test_tfidf)

print("Model with 1-3 grams trained successfully.")
print("Training shape:", X_train_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)

accuracy = accuracy_score(y_test, lr_balanced_data_predictions)

print("Accuracy:", accuracy)
print(classification_report(y_test, lr_balanced_data_predictions))

def predict_emotion_final(poem):
    cleaned = clean_arabic_text(poem)
    poem_vector = tfidf.transform([cleaned])
    prediction = lr_model_balanced_data.predict(poem_vector)[0]
    return prediction

new_poem = "أحببتُكِ حبًّا لو تكلّمَ، لقال للعالم: ما خُلِقَ الوفاءُ إلا لها."
predict_emotion_final(new_poem)

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, lr_balanced_data_predictions)

plt.figure(figsize=(6,5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=lr_model_balanced_data.classes_,
    yticklabels=lr_model_balanced_data.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""The confusion matrix reveals strong overlap between emotional classes, particularly between love and sadness, indicating that Arabic poetry frequently expresses blended emotional states. Joy was the most distinguishable class, while sadness showed the highest ambiguity."""

def predict_emotion_final(poem):
    cleaned = clean_arabic_text(poem)
    poem_vector = tfidf.transform([cleaned])

    prediction = lr_model_balanced_data.predict(poem_vector)[0]
    probabilities = lr_model_balanced_data.predict_proba(poem_vector)[0]

    print("Original poem:")
    print(poem)

    print("\nCleaned poem:")
    print(cleaned)

    print("\nPredicted emotion:")
    print(prediction)

    print("\nProbabilities:")
    for emotion, prob in zip(lr_model_balanced_data.classes_, probabilities):
        print(f"{emotion}: {prob:.3f}")

    return prediction

test_poem = "أحبك يا نور قلبي وبهجة أيامي"

predict_emotion_final(test_poem)

test_poem = "وما كنت ممن يدخل العشق قلبه/ ولكن من يبصر جفونك يعشق"
predict_emotion_final(test_poem)

user_poem = input("Enter your poem: ")

predict_emotion_final(user_poem)

user_poem = input("Enter your poem: ")

predict_emotion_final(user_poem)

user_poem = input("Enter your poem: ")

predict_emotion_final(user_poem)

import joblib

joblib.dump(lr_model_balanced_data, "arabic_poem_emotion_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model saved successfully.")

"""**Conclusion**

This project demonstrated the application of Natural Language Processing (NLP) and Machine Learning techniques for classifying emotions in Arabic poetry into three categories: joy, love, and sadness. Through a complete text mining pipeline—including data cleaning, Arabic text normalization, class balancing, TF-IDF feature extraction, and supervised classification—the final optimized Logistic Regression model achieved approximately 60.7% accuracy.
The results showed that feature engineering significantly influenced performance, particularly the use of unigrams, bigrams, and trigrams, which improved the model’s ability to capture meaningful poetic expressions. Balancing the dataset also reduced model bias and produced more consistent predictions across emotion classes.
However, emotion classification in Arabic poetry remains challenging due to the rich figurative language, semantic ambiguity, and overlap between emotional states such as love, longing, and sadness. Despite these challenges, the developed model successfully provides a practical framework for automatic emotion detection in Arabic literary text and demonstrates the potential of NLP techniques in Arabic text mining applications.

"""